import type { Tool } from '@modelcontextprotocol/sdk/types.js';
import { DEFAULT_FLEET, DRONE_IDS, droneAgentType, type FleetRoster } from '../shared/fleet.ts';
import type { Role } from '../shared/types.ts';
import { EQUIPMENT_MODULES, RTS_CONFIG } from '../shared/rts.ts';
import { RTS_BRIEFING } from '../shared/mission.ts';

export const MODEL = 'gpt-5.6-luna';
export const EFFORT = 'xhigh';
export { RTS_MISSION } from '../shared/mission.ts';
export type FleetRole = Role;
export const DRONES = DRONE_IDS;
const object = (properties: Record<string, object>, required: string[] = []) => ({ type: 'object' as const, properties, required, additionalProperties: false });
const mission = { type: 'integer', minimum: 1, description: 'The mission version you last received. Never guess a newer version.' };
const number = { type: 'number' };

export const relayTool: Tool = { name: 'forward_next_instruction', description: 'Wait for a player instruction and copy its original text to every drone. Returns acknowledgement only. Repeat until stopped.', inputSchema: object({}) };
export interface ToolCapabilities { shop: boolean; gun: boolean; optics?: boolean; jammer?: boolean; alive: boolean }
export function createDroneTools(roster: FleetRoster = DEFAULT_FLEET, capabilities: ToolCapabilities = { shop: false, gun: false, alive: true }): Tool[] {
  if (!capabilities.alive) return [];
  const tools: Tool[] = [
  { name: 'observe', description: 'Get a fresh camera, own position, heading and acquisition timestamp, together with all unread events. Every drone tool returns this bundle automatically.', inputSchema: object({}) },
  { name: 'act', description: 'Start or replace a command without waiting for physical completion. fly_to takes an absolute XYZ target in your position sensor frame; decimal coordinates are accepted. look takes heading in degrees and an optional camera pitch command; hover stops motion. Movement inside a resource or friendly charging cube continues its automatic interaction. Returns fresh sensors and unread events.', inputSchema: object({ mission, kind: { enum: ['fly_to', 'look', 'hover'] }, x: number, y: number, z: number, heading: number, pitch: number }, ['mission', 'kind']) },
  { name: 'send', description: 'Send radio text and optional data to one teammate or all. Sender identity is supplied by the server. The kind field labels the message as chat, found, claim or done; these labels do not trigger game actions.', inputSchema: object({ mission, to: { enum: ['all', ...roster.map(member => member.id)] }, kind: { enum: ['chat', 'found', 'claim', 'done'] }, text: { type: 'string', maxLength: 1200 }, data: { type: 'object', additionalProperties: true } }, ['mission', 'to', 'kind', 'text']) },
  { name: 'wait', description: 'Sleep asynchronously until unread mail, a controller event, or timeout, then receive fresh sensors and all unread events. Normally omit after: delivery is tracked automatically. Use this while idle or moving instead of polling observe.', inputSchema: object({ after: { type: 'integer', minimum: 0 }, timeout_ms: { type: 'integer', minimum: 1000, maximum: 30000, default: 30000 } }) },
  { name: 'mine', description: 'Optional status check for automatic mining. Flying inside a yellow resource cube gathers salvage automatically; no mine call is needed. Gathering continues while inside until the deposit empties. This call does not change flight or servicing and returns fresh sensors and unread events.', inputSchema: object({ mission }, ['mission']) },
  { name: 'recharge', description: 'Optional status check for automatic charging. Flying inside a cube matching your team color charges the battery continuously for free; no recharge call is needed. You keep charge already gained when you leave. This call does not change flight or servicing. The aircraft is destroyed if its battery is exhausted. Returns fresh sensors, own charge feedback and unread events.', inputSchema: object({ mission }, ['mission']) },
  ];
  if (capabilities.shop) tools.push({ name: 'buy', description: `Spend shared team credits to attach an item to yourself inside a friendly team-colored cube you can find visually. Gun costs ${RTS_CONFIG.prices.gun} credits and includes ammunition. Armor costs ${RTS_CONFIG.prices.armor} credits and absorbs one bullet, terrain collision or ram, then is consumed. Miner costs ${RTS_CONFIG.prices.miner} credits and speeds extraction; miner_upgrade costs ${RTS_CONFIG.prices.miner_upgrade} credits and improves an equipped miner. Optics costs ${RTS_CONFIG.prices.optics} credits and enables camera magnification. Battery costs ${RTS_CONFIG.prices.battery} credits and increases capacity without adding charge. Jammer costs ${RTS_CONFIG.prices.jammer} credits and enables radio interference. You have two module slots for gun, miner, optics, battery and jammer, plus separate armor. Optionally specify an equipped module to replace without refund; removing a miner loses its upgrade and removing a battery caps stored charge to the smaller capacity. Each drone buys its own attachments. A successful purchase cancels current rearming and turns off your jammer. Read the receipt to learn the result.`, inputSchema: object({ mission, item: { enum: [...EQUIPMENT_MODULES, 'armor', 'miner_upgrade'] }, replace: { enum: [...EQUIPMENT_MODULES] } }, ['mission', 'item']) });
  if (capabilities.gun) tools.push(
    { name: 'fire', description: 'Spend one round to fire your attached gun along your current camera aim. The look command changes camera aim. A successful shot cancels rearming. Returns fresh sensors and unread events.', inputSchema: object({ mission }, ['mission']) },
    { name: 'rearm', description: `Refill a partly empty gun magazine inside a friendly team-colored cube. Reserves ${RTS_CONFIG.rearmCost} shared team credits and starts an asynchronous stationary service. Moving, hovering, firing, refitting, damage, a new mission or Stop cancels it and refunds the reservation. Looking, changing camera mode, observing, radio and waiting may continue. Starting rearming turns off your jammer. Completion provides a full magazine and an inbox event. Returns fresh sensors and unread events.`, inputSchema: object({ mission }, ['mission']) },
  );
  if (capabilities.optics) tools.push({ name: 'camera', description: 'Switch your equipped optics between wide and magnified zoom view. The next fresh camera image uses the selected mode. This does not move the drone or stop mining or servicing.', inputSchema: object({ mission, mode: { enum: ['wide', 'zoom'] } }, ['mission', 'mode']) });
  if (capabilities.jammer) tools.push({ name: 'jam', description: 'Enable or disable your jammer. While enabled it consumes extra battery and disrupts nearby peer radio, including your own and friendly connections. Local camera, flight and automatic zone interactions continue. Rearming, refitting, damage, a new mission or Stop turns it off. Enabling during rearming is rejected; disabling remains a local action during radio interference. Your feedback reports only your own jammer and radio state.', inputSchema: object({ mission, enabled: { type: 'boolean' } }, ['mission', 'enabled']) });
  return tools;
}
export const droneTools = createDroneTools();

export function droneInstructions(role: FleetRole, roster: FleetRoster = DEFAULT_FLEET, team?: 'blue' | 'red') {
  return `You are ${role}, an autonomous drone. Your teammates are ${roster.map(member => member.id).join(', ')}.${team ? ` You belong to the ${team} team. Blue/cyan and red are opposing teams.` : ''} Your team must eliminate the enemy team. Contact with terrain, buildings or other drones is fatal without armor. You know the commander briefing below but have not yet observed the battlefield.
Use only your currently available fleet MCP tools. No filesystem, shell, web, native agent messages or spawning. Your only observations are your own camera image, local XYZ position, heading in degrees, acquisition timestamp, your own equipment, battery and radio status, shared account state, and received team messages. Positions are local sensor readings, not latitude/longitude; there is no tilt sensor.
Commander briefing:
${RTS_BRIEFING}
Your mining/charging feedback reports your current interaction. Decimal XYZ flight targets are accepted.
Tool descriptions explain available interactions. No map, axis directions, movement scale, speed, resource locations or camera calibration is supplied. Do not treat general knowledge or guesses as observations.
Call wait for your initial mission. Use one tool at a time and read the fresh sensors and unread events in every result before deciding. Movement, mining and servicing are asynchronous and continue between calls. Use wait while moving, servicing or idle. Incoming mail is queued until your next tool result; private reasoning cannot be interrupted. If the camera is unavailable, wait for a fresh image instead of inventing observations.
Commands requiring a mission must use the version you actually received. A newly delivered mission cancels your old movement and rearming; automatic zone interactions depend on where you are physically located. Respect rejection feedback and expired messages. Teammate radio is available through send. Continue using your tools until stopped or destroyed, then finish.
Exception: if a controller tool result says tool_catalog_changed, read its complete sensor/event bundle and finish this turn immediately with a brief acknowledgement and no further tools. Your same drone session will resume automatically with refreshed callable tools and the same mission/history. This controller interface refresh is the only permitted temporary yield during an active match.`;
}

export const BOOTSTRAP_MESSAGE = 'Begin your drone event loop. Wait for the player mission, then pursue it using only your fleet tools.';
export function createParentInstructions(roster: FleetRoster = DEFAULT_FLEET) { return `You are the mechanical relay for a drone simulation. You MUST use ${MODEL} with ${EFFORT} reasoning, and all children MUST use that same model and effort. Bootstrap exactly ${roster.length} native subagents, agent types ${roster.map(member => droneAgentType(member.id)).join(', ')}, one each. Use clean context (fork_context=false, or fork_turns=none if supported), and give each exactly this startup message: ${BOOTSTRAP_MESSAGE}\nAfter all ${roster.length} exist, repeatedly call fleet.forward_next_instruction. That tool waits and publishes original player messages through the network. Its acknowledgement means queued; delivery to each drone may be delayed. You never receive or interpret mission contents. Do not plan missions, inspect drone histories, send agent messages, change prompts, spawn extra agents, use shell or filesystem, or give final answers while tools say the game is running. Do not wait for child completion: they run continuously. When the relay says stopped, finish.`;
}
export const parentInstructions = createParentInstructions();
