import type { Tool } from '@modelcontextprotocol/sdk/types.js';
import { DEFAULT_FLEET, DRONE_IDS, droneAgentType, type FleetRoster } from '../shared/fleet.ts';
import type { Role } from '../shared/types.ts';
import { CARGO_CONFIG, EQUIPMENT_MODULES, RTS_CONFIG } from '../shared/rts.ts';
import { RTS_BRIEFING } from '../shared/mission.ts';
import { DEFAULT_AGENT_BACKEND } from './agent-backend.ts';
import { CAMERA_PITCH_LIMITS, FLIGHT_PROFILES } from './drone-motion.ts';
import { LOCAL_SENSOR_CONFIG } from './local-sensors.ts';
import { ONBOARD_PROFILE } from '../shared/onboard.ts';
import { DRONE_HOST_LIBRARIES } from '../shared/actor-environment.ts';
import { ROUTINE_LIMITS } from './routine-runner.ts';

export const MODEL = DEFAULT_AGENT_BACKEND.model;
export const EFFORT = DEFAULT_AGENT_BACKEND.effort;
export { RTS_MISSION } from '../shared/mission.ts';
export type FleetRole = Role;
export const DRONES = DRONE_IDS;
const object = (properties: Record<string, object>, required: string[] = []) => ({ type: 'object' as const, properties, required, additionalProperties: false });
const mission = { type: 'integer', minimum: 1, description: 'The objective version you last actually received. Never guess a newer version.' };
const number = { type: 'number' };
const provenance = {
  observation_sequence: { type: 'integer', minimum: 0, description: 'Optional originating observation sequence actually delivered to you.' },
  event_cursor: { type: 'integer', minimum: 0, description: 'Optional originating event cursor actually delivered to you.' },
};
const point = object({ x: number, y: number, z: number }, ['x', 'y', 'z']);
const path = { type: 'string', minLength: 1, maxLength: 128, description: 'A relative path in your private onboard workspace, at most 128 UTF-8 bytes; never a host path.' };
const job = { type: 'string', minLength: 1, maxLength: 128 };

export const relayTool: Tool = { name: 'forward_next_instruction', description: 'Wait for queued original team instructions and forward their exact text to every drone. Returns acknowledgement only. Repeat until stopped.', inputSchema: object({}) };
export interface ToolCapabilities { shop: boolean; gun: boolean; optics?: boolean; jammer?: boolean; alive: boolean; onboard?: boolean }
export function createDroneTools(roster: FleetRoster = DEFAULT_FLEET, capabilities: ToolCapabilities = { shop: false, gun: false, alive: true }, team?: 'blue' | 'red'): Tool[] {
  if (!capabilities.alive) return [];
  const tools: Tool[] = [
    { name: 'observe', description: 'Acquire a fresh camera image plus timestamped own telemetry, current job/storage/interaction feedback and the next unread local-event/mail slice. Event delivery uses a 128 KiB slice budget; hasMore:true means unread events remain for your next tool result or wait. Only included events are consumed. Every direct tool and exchange returns one fresh aggregate bundle. Image pose is capture-time pose; current telemetry may be newer. Sensors do not classify or locate world objects.', inputSchema: object({}) },
    { name: 'act', description: `Submit an asynchronous vehicle command. fly_to uses absolute decimal XYZ in the documented local vehicle frame; accepted does not mean arrived. travel limits speed/acceleration to ${FLIGHT_PROFILES.travel.maxSpeed} local units/s and ${FLIGHT_PROFILES.travel.acceleration} local units/s²; precision uses ${FLIGHT_PROFILES.precision.maxSpeed} and ${FLIGHT_PROFILES.precision.acceleration}. Cargo reduces maximum speed by 20%. look sets heading and camera pitch in degrees (${CAMERA_PITCH_LIMITS.min} down through ${CAMERA_PITCH_LIMITS.max} up). hover cancels movement and requests physical braking. One movement writer owns the vehicle; explicitly replace an existing route/routine to take over. Camera and radio can continue during flight. Assistance uses 26 fixed directional swept-sphere beams with radius ${LOCAL_SENSOR_CONFIG.proximityRadius} and range ${LOCAL_SENSOR_CONFIG.proximityRange} local units, plus a separate downward pencil range of ${LOCAL_SENSOR_CONFIG.downwardRange}; samples expire after ${LOCAL_SENSOR_CONFIG.maxAgeMs} host milliseconds. Unsupported coverage/obstruction can stop/mark blocked; this never chooses another route or guarantees collision immunity.`, inputSchema: object({ mission, ...provenance, kind: { enum: ['fly_to', 'look', 'hover'] }, x: number, y: number, z: number, heading: number, pitch: { type: 'number', minimum: CAMERA_PITCH_LIMITS.min, maximum: CAMERA_PITCH_LIMITS.max }, profile: { enum: ['travel', 'precision'] }, replace: { type: 'boolean' } }, ['mission', 'kind']) },
    { name: 'send', description: `Queue bounded radio text and optional data to one teammate or all teammates.${team === 'blue' ? ' to: player sends ordinary chat to the blue commander.' : ''} Sender identity is bound to you. Labels chat/found/claim/done/status describe content; all text uses the same durable radio. Undelivered transmissions retry for up to 120 host seconds. Received text stays in your bounded inbox until included in a tool result, even while you think. A later status never overwrites unread text. A local queue receipt, recipient storage, inclusion in a tool bundle, explicit reply and completed action are different stages. Sending establishes neither reading nor agreement. Ordinary chat does not replace the objective or cancel jobs.`, inputSchema: object({ mission, ...provenance, to: { enum: ['all', ...roster.map(member => member.id), ...(team === 'blue' ? ['player'] : [])] }, kind: { enum: ['chat', 'found', 'claim', 'done', 'status'] }, text: { type: 'string', maxLength: 1200 }, data: { type: 'object', additionalProperties: true } }, ['mission', 'to', 'kind', 'text']) },
    { name: 'wait', description: 'Wait asynchronously for unread mail, a relevant local controller event, cancellation, or timeout, then receive fresh sensors and the next unread event slice. hasMore:true indicates further unread events; another wait can deliver them without waiting for new mail. Normally omit after: delivery is tracked automatically. Continuous local control, radio and valid routines continue while the model waits or thinks.', inputSchema: object({ after: { type: 'integer', minimum: 0 }, timeout_ms: { type: 'integer', minimum: 1000, maximum: 30000, default: 30000 } }) },
    { name: 'route', description: 'Start/status/cancel a bounded ordered list of caller-chosen absolute XYZ waypoints. start returns a job ID immediately; each step completes before the next. travel/precision selects vehicle response, not a route. Use replace:true to cancel another movement writer explicitly. Status distinguishes accepted/running/blocked/completed/cancelled/failed. A blocked route stops for your next decision. No global pathfinding is provided.', inputSchema: object({ mission, ...provenance, op: { enum: ['start', 'status', 'cancel'] }, waypoints: { type: 'array', minItems: 1, maxItems: 32, items: point }, profile: { enum: ['travel', 'precision'] }, replace: { type: 'boolean' }, job_id: job }, ['mission', 'op']) },
    { name: 'workspace', description: 'List/read/write/delete/stat your private onboard Markdown, JSON and small JavaScript files. Paths are virtual and isolated. Writes and replacements are atomic and count UTF-8 bytes, names, metadata and temporary staging. Limits: 2 MiB writable workspace, 64 KiB per file, 256 files. stat reports own partition use/free space. The 1 MiB logs/cache partition splits into 512 KiB unread local events and 512 KiB rotating diagnostics; native durable radio has a separate 4 MiB quota. Storage-full errors preserve existing files. Files survive turns within this match; a new match is empty and destruction revokes access.', inputSchema: object({ mission, op: { enum: ['list', 'read', 'write', 'delete', 'stat'] }, path, content: { type: 'string', maxLength: 65536 } }, ['mission', 'op']) },
    { name: 'routine', description: 'Start/status/cancel a private JavaScript module from your workspace. start accepts caller input, returns a job ID promptly, and uses immutable source versions. One movement writer; replace:true explicitly cancels another writer. The frozen drone SDK offers telemetry(), camera(), act(args), send(args), sleep(ms), files.read/write/list/stat/delete and permitted equipment calls. Example syntax only: const sample = await drone.telemetry(); await drone.files.write("sample.json", JSON.stringify(sample)); Use global input for your caller data. Relative own-workspace .js/.mjs imports only; no shell, process, fetch, sockets, host files, arbitrary packages or hidden map. Default limits are 32 MiB guest heap, 20 ms worker CPU per slice, 250 ms worker CPU per wall second, 64 SDK calls per second, eight pending calls, two seconds per host operation and 120 seconds total wall time. Execution and storage budgets are enforced, and failure cancels owned movement. Radio loss alone does not stop valid local execution.', inputSchema: object({ mission, ...provenance, op: { enum: ['start', 'status', 'cancel'] }, path, input: { type: 'object', additionalProperties: true }, replace: { type: 'boolean' }, job_id: job }, ['mission', 'op']) },
    { name: 'transfer', description: 'Offer a private workspace file to one teammate through bounded low-priority radio chunks, or list/status/import/cancel a transfer. Announced bytes and content hash must verify before recipient-chosen import. Received code stays inert; imports never execute it. Each recipient pays its own workspace space; partial transfers share the 1 MiB staging partition with atomic writes and a 256 KiB native-transaction reserve. No shared team folder, archives or compression. Offer uses your path; import uses the recipient-chosen destination path.', inputSchema: object({ mission, operation: { enum: ['offer', 'list', 'status', 'import', 'cancel'] }, to: { enum: roster.map(member => member.id) }, path, transferId: { type: 'string', maxLength: 128 } }, ['mission', 'operation']) },
  ];
  if (capabilities.shop) tools.push({ name: 'buy', description: `Fit equipment to yourself inside a friendly base service volume using shared salvage. Gun and cargo each cost ${RTS_CONFIG.prices.gun}; armor costs ${RTS_CONFIG.prices.armor}. Two module slots; armor is separate. Your free grip carries ${CARGO_CONFIG.gripCapacity} salvage; cargo module carries ${CARGO_CONFIG.moduleCapacity} total. Gun initially includes ${RTS_CONFIG.magazineSize} rounds. Explicit replace discards an equipped module without refund. Refitting does not refill ammunition. Each drone buys its own item. A purchase cancels timed rearming. Read the atomic receipt; no purchase targets another drone.`, inputSchema: object({ mission, ...provenance, item: { enum: [...EQUIPMENT_MODULES, 'armor'] }, replace: { enum: [...EQUIPMENT_MODULES] } }, ['mission', 'item']) });
  if (capabilities.gun) tools.push(
    { name: 'fire', description: 'Spend one finite round to fire your attached gun along your actual current camera aim. look changes aim through the controller. Carrying cargo permits firing. A successful shot cancels rearming. No target ID, automatic aiming or hidden hit receipt is available.', inputSchema: object({ mission, ...provenance }, ['mission']) },
    { name: 'rearm', description: `Reserve ${RTS_CONFIG.rearmCost} shared salvage to refill a partly empty gun to ${RTS_CONFIG.magazineSize} rounds after ${RTS_CONFIG.serviceDuration} uninterrupted simulation seconds at friendly base service. Motion, hover, firing, refitting, damage, a received new objective or Stop cancel and refund exactly once. Looking, camera mode, observing, radio, waiting and unloading can continue. Acceptance is not ammunition completion.`, inputSchema: object({ mission, ...provenance }, ['mission']) },
  );
  if (capabilities.optics) tools.push({ name: 'camera', description: 'Select wide or magnified zoom on your equipped optics. The next acquired image uses that projection and reports its calibration. This does not choose a view target, classify objects, move the drone or stop service.', inputSchema: object({ mission, ...provenance, mode: { enum: ['wide', 'zoom'] } }, ['mission', 'mode']) });
  const compatible = tools.filter(tool => ['act', 'route', 'send', 'camera', 'buy', 'fire', 'rearm'].includes(tool.name)).map(tool => tool.name);
  tools.push({ name: 'exchange', description: 'Submit up to eight compatible operations with one aggregate fresh camera/telemetry/inbox bundle. Each unique operation ID gets its own accepted/rejected/queued outcome; completed side effects are not rolled back if another operation fails. At most one movement writer; dependent actions belong in an ordered route/routine. Operation args inherit the outer mission. No waits, nested exchanges, file transfers or routine execution inside a batch. Read all outcomes before deciding.', inputSchema: object({ mission, ...provenance, operations: { type: 'array', minItems: 1, maxItems: 8, items: object({ id: { type: 'string', minLength: 1, maxLength: 64 }, tool: { enum: compatible }, args: { type: 'object', additionalProperties: true } }, ['id', 'tool', 'args']) } }, ['mission', 'operations']) });
  return capabilities.onboard === false ? tools.filter(tool => !['workspace', 'routine', 'transfer'].includes(tool.name)) : tools;
}
export const droneTools = createDroneTools();

export function droneInstructions(role: FleetRole, roster: FleetRoster = DEFAULT_FLEET, team?: 'blue' | 'red') {
  return `${role}, autonomous drone.${team ? ` ${team} team.` : ''} Team roster: ${roster.map(member => member.id).join(', ')}.
Win: eliminate every enemy while one of us survives. Follow the common briefing below.
Inputs: own pixels, XYZ/velocity, heading/camera orientation, finite ranges, timestamped equipment/cargo/jobs/storage/balance and received mail. One unit is ten meters; no body roll/pitch dynamics. Vehicle calibration is supplied below; battlefield knowledge is not. Preserve source/time/uncertainty in estimates.
Wait for the objective; read each fresh direct/exchange bundle, draining hasMore via wait. Never invent missing/stale frames. Admission is not completion; one movement writer, explicit replacement. Exchange permits ${ONBOARD_PROFILE.maxBatchOperations} compatible operations without rollback; dependencies need routes/routines. Use received mission versions; objective changes cancel work, chat does not. Respect rejection/backpressure and lifecycle cancellation. Keep reasoning/radio concise; continue until stopped/destroyed.
Compute: ${MODEL}/${EFFORT}; fleet tools, private QuickJS and frozen drone SDK only. Inference hardware/weights are exempt. Application partitions runtime/workspace/radio/staging/logs: ${Object.values(ONBOARD_PROFILE.storage).map(bytes => bytes / 1024 ** 2).join('/')} MiB; files ≤${ONBOARD_PROFILE.maxFileBytes / 1024} KiB, ${ONBOARD_PROFILE.maxFiles} files. QuickJS: ${ROUTINE_LIMITS.heapBytes / 1024 ** 2} MiB heap, ${ROUTINE_LIMITS.sliceMs} ms CPU/slice, ${ROUTINE_LIMITS.cpuMsPerSecond} ms CPU/s, ${ROUTINE_LIMITS.operationsPerSecond} SDK calls/s, ${ROUTINE_LIMITS.pendingCalls} pending, ${ROUTINE_LIMITS.hostDeadlineMs / 1000}s/operation, ${ROUTINE_LIMITS.wallTimeMs / 1000}s/run. Relative own-module imports only; optional guest libraries: none (${ONBOARD_PROFILE.optionalLibraryBytes / 1024} KiB ceiling). Host-only libraries: ${DRONE_HOST_LIBRARIES.map(library => library.name).join(', ')}. No host files, shell, web, sockets, arbitrary packages, spawning or native agent messages. Transfers require verified recipient import; never auto-execute received code.
On tool_catalog_changed, read the complete result, then finish this turn immediately with a brief acknowledgement and no further tools; the same actor resumes with refreshed tools and preserved objective/history.
Sensor encoding (fleet-observation/5): directions:"xyz26" enumerates [-1,0,1] triples, X outer/Y middle/Z inner, omitting [0,0,0], each divided by Math.hypot(x,y,z); other directions are explicit [x,y,z]. distance/validity/radius/maxDistance are scalars for all beams or arrays in that order; unknown shapes remain named-object arrays. currentTelemetry.ranges.proximity sameAs:"sensors.ranges.proximity" references that exact fresh column object within this bundle only; current timestamps/origin/downward remain separate. Null/out-of-range is not an obstacle. Acquired camera pose and newer telemetry have separate timestamps.
Commander briefing:
${RTS_BRIEFING}`;
}

export const BOOTSTRAP_MESSAGE = 'Begin your drone event loop. Wait for the team objective, then pursue it using only your fleet tools.';
export function createParentInstructions(roster: FleetRoster = DEFAULT_FLEET) { return `You are the mechanical relay for a drone simulation. You MUST use ${MODEL} with ${EFFORT} reasoning, and all children MUST use that same model and effort. Bootstrap exactly ${roster.length} native subagents, agent types ${roster.map(member => droneAgentType(member.id)).join(', ')}, one each. Use clean context (fork_context=false, or fork_turns=none if supported), and give each exactly this startup message: ${BOOTSTRAP_MESSAGE}\nAfter all ${roster.length} exist, repeatedly call fleet.forward_next_instruction. That tool waits and publishes original team instructions through the network. Its acknowledgement means queued; delivery to each drone may be delayed. You never receive or interpret mission contents. Do not plan missions, inspect drone histories, send agent messages, change prompts, spawn extra agents, use shell or filesystem, or give final answers while tools say the game is running. Do not wait for child completion: they run continuously. When the relay says stopped, finish.`;
}
export const parentInstructions = createParentInstructions();
