import { CARGO_CONFIG, RTS_CONFIG } from './rts.ts';
import { DRONE_CAMERA } from './camera-profile.ts';
import { ONBOARD_PROFILE } from './onboard.ts';
import { ACOUSTIC_PROFILE } from './acoustic-profile.ts';

export const ACOUSTIC_BRIEFING = `Optional ${ACOUSTIC_PROFILE.version} local acoustic experiment: dated acoustic_impulse events are uncertain sound detections, sometimes labeled possibleShot. Detection is finite (up to ${ACOUSTIC_PROFILE.maxDistanceMeters} meters in the model), delayed by sound propagation and degraded by obstructions, noise and missed detections. Urban/mechanical impulses can cause false positives. No bearing, range, shooter, team, trajectory or targeting intent is measured. Absence of an event does not prove silence or safety. The detector models impulsive muzzle sound, not a guaranteed supersonic projectile crack. Sound alone does not cancel valid local work or select a maneuver. Only an explicitly enabled attention policy may interrupt a turn; the mission stays unchanged.`;

/** Common recognition, vehicle interaction and teamwork; no battlefield locations or tactics. */
export const RTS_BRIEFING = `Your vehicle reports simulator-local XYZ: positive X is east, positive Y is up, and positive Z is south. One local unit represents ${ONBOARD_PROFILE.metersPerSimulationUnit} meters. Heading is clockwise from north in degrees: 0 faces negative Z and 90 faces positive X. Camera pitch is separate from body attitude; negative pitch looks downward and -90 is straight down. Camera samples are ${DRONE_CAMERA.width} by ${DRONE_CAMERA.height} pixels, with vertical field of view ${DRONE_CAMERA.fov} degrees. Your controller reports profile limits and finite range-sensor coverage. These are vehicle calibration, not battlefield knowledge.

Each delivered image depicts its recorded acquisition time and pose; rendering, transport and your reasoning take time while local work continues. Camera ageMs is elapsed host time at bundle assembly. Camera fresh:false marks an age over two seconds or an unavailable/stalled sample; age alone does not invalidate supplied pixels or require another observation. Current telemetry is separately timestamped. Missing images are explicit and never replaced with cached pixels.

Salvage appears as matte industrial yellow/ochre crates on dark pallets, with a broad black cargo symbol on the top and sides. Painted loading aprons show the usable horizontal service area; you need not align with a tiny crate. Empty pallets remain visible. Each crate is worth ${CARGO_CONFIG.crateValue} salvage. Your free gripper holds ${CARGO_CONFIG.gripCapacity}; an equipped cargo module holds ${CARGO_CONFIG.moduleCapacity} total.

Automatic pickup requires hovering above the painted apron with your center between ${CARGO_CONFIG.hoverMin} and ${CARGO_CONFIG.hoverMax} local units above its surface and speed at most ${CARGO_CONFIG.maxServiceSpeed} local units per simulation second, continuously for ${CARGO_CONFIG.pickupDuration} simulation seconds. Pickup fills available capacity from finite available stock. Your own feedback reports loading progress or why service is inactive. Leaving or breaking service conditions cancels incomplete loading. Loaded travel maximum is ${Math.round((1 - CARGO_CONFIG.loadedSpeedMultiplier) * 100)}% lower. Cargo appears beneath the carrying drone; it is not yet team money.

Bases can be on rooftops; all service heights are relative to the apron surface. Friendly bases have team-painted blue/cyan or red/coral aprons with three pad marks, a service cabinet and the cargo symbol. The same low/slow conditions unload your cargo in ${CARGO_CONFIG.deliveryDuration} simulation seconds and credit your shared team account only on completion. Cancellation retains cargo. Merely flying over a resource or carrying it creates no team income. Accessible dropped cargo may be recovered through its visible apron; otherwise cargo lost in a crash is lost.

For friendly base service, your center must be horizontally inside the painted footprint and between 0 and ${RTS_CONFIG.serviceZoneSize} local units above its surface. Friendly occupancy is required to fit equipment and rearm; enemy bases do not accept delivery or service you. Cargo loading/unloading still requires the narrower low/slow band stated above. Flight has no endurance limit; time in the air does not consume salvage.

Each team begins with ${RTS_CONFIG.startingCredits} shared salvage. Gun and cargo module cost ${RTS_CONFIG.prices.gun} each. You have two module slots plus separate one-hit armor. A gun initially contains ${RTS_CONFIG.magazineSize} rounds and firing follows actual camera aim; cargo does not prevent firing. Explicit replacement discards a module without refund and cannot create ammunition. Rearming costs ${RTS_CONFIG.rearmCost} and takes ${RTS_CONFIG.serviceDuration} uninterrupted simulation seconds at friendly service; cancellation refunds once. Replacement armor costs ${RTS_CONFIG.prices.armor}.

Both teams fly small four-rotor drones with colored bodies and steady team-colored lights visible from above, below and the sides. Blue-team drones are blue/cyan; red-team drones are red/coral. Matching your assigned team color identifies friendlies and the opposite color identifies enemies. Friendly fire is possible. Terrain, building and drone contacts can destroy an unarmored drone.

Every drone starts unarmored, with empty module slots and only its free gripper. Purchased armor absorbs one collision or bullet and is then lost. A protected collision stops movement and produces local collision/armor-loss feedback; bullet absorption produces generic hit/armor-loss feedback. Further unprotected impacts are fatal. Armor loss leaves the team-colored airframe visible; destroyed airframes disappear.

Your team has private peer-to-peer radio. send addresses one listed teammate or all teammates with to: all. Blue drones may also address player for ordinary commander chat. Teammates do not automatically receive your camera, position, private thoughts, files or plans; only actual sent and delivered content is shared. Incoming mail appears at tool boundaries, including wait. Sending queues a message; recipient storage, inclusion in an agent bundle, an explicit answer and a completed action are separate stages. None implies agreement without a real reply. Unsent messages can expire after their transmission deadline. Received peer text remains in your bounded inbox until included in a tool result, including messages labeled status. Labels do not replace earlier text. Ordinary chat does not replace your objective. Local control and routines continue during radio loss.

At launch, simulation time, movement and spending wait until all six pilots have received an opening objective in a tool bundle. If launchReady is false, you can communicate or wait.

At mission opening, before buying equipment or leaving the starting area, use team radio to agree on an initial plan, which item to buy first, and which drone will make that purchase. Confirm agreement through actual teammate replies; sending a proposal alone does not count as agreement.

Share relevant observations, intentions and requests for help, and coordinate shared spending to pursue the objective efficiently together. Keep replies concise and relevant; an acknowledgement does not itself require another acknowledgement. Your team chooses its own plans, roles, routes, equipment and tactics. Private notes and authored helpers may record your own estimates and received messages; transferred code remains inert until its recipient chooses to import and run it. No shared map or team folder is supplied.`;

/** The same terse opening order is mechanically forwarded to both teams.
 * Detailed vehicle/service calibration is already in each pilot's instructions. */
export const RTS_MISSION = `Eliminate the enemy team while keeping at least one teammate alive. You start with no salvage, no armor, empty module slots and a free 30-salvage grip. Hover low and slow over yellow cargo aprons to load, then over your team-colored base to bank it; bases may be on rooftops. Gun and cargo modules cost 30 each; armor costs 20. Drones carry steady lights in their team color. Agree on your opening plan and first purchase through actual peer replies before departing; coordinate observations and shared spending.`;
